server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;

    # 1. RUTA PARA ANGULAR (El Frontend)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. PUENTE AL BACKEND (¡LA MAGIA DEL PROXY!)
    # Nginx intercepta todo lo que empiece con /api y se lo manda al contenedor de Java
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Caché para imágenes y estilos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4|webm)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}