spring.application.name=GestionClinica

# Configuración de Spring Boot (Lee el .env si estás corriendo desde tu IDE)
spring.config.import=optional:file:.env[.properties]

# Configuración del Servidor
server.port=${SERVER_PORT:8080}

# ==========================================================
# CONEXIÓN A LA BASE DE DATOS (Lista para Local, Docker y Nube)
# ==========================================================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:clinic_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================================
spring.jpa.hibernate.ddl-auto=update
# Apagamos los logs de SQL para que Docker y la nube no se saturen de texto
spring.jpa.show-sql=false 
spring.jpa.properties.hibernate.format_sql=true

# ==========================================================
# SEGURIDAD (Mapeo opcional por si lo llamas desde @Value)
# ==========================================================
jwt.secret=${JWT_SECRET:GestionClinicaJWTSecretKey2026MuySeguraParaProduccion}